default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: admin

development:
  <<: *default
  database: f_twitter_development

test:
  <<: *default
  database: f_twitter_test

production:
  <<: *default
  database: f_twitter_production
  username: f_twitter
  password: <%= ENV['F_TWITTER_DATABASE_PASSWORD'] %>
